//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DALEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrdersRefs = new HashSet<OrdersRef>();
        }
    
        public long MainOrderID { get; set; }
        public System.DateTime Date { get; set; }
        public long CustomerID { get; set; }
        public short StatusID { get; set; }
        public string Comments { get; set; }
        public System.DateTime LastUpdate { get; set; }
        public Nullable<long> LastStaffUpdated { get; set; }
    
        public virtual DeliveryStatu DeliveryStatu { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrdersRef> OrdersRefs { get; set; }
    }
}
